amiibofindr/apps/amiibo/urls.py
# coding: utf-8

# django
from django.conf.urls import url, patterns
from django.utils.translation import ugettext_lazy as _

# home
from .views import (
    AmiiboView, AmiiboCardView, AmiiboFigureView,
    CollectionView, CollectionCardView, CollectionFigureView,
    UserAmiiboView
)

urlpatterns = patterns(
    '',
    url(_('^cards$'),
        CollectionCardView.as_view(),
        name='cards-all'),
    url(_(r'^figures$'),
        CollectionFigureView.as_view(),
        name='figures-all'),

    url(_(r'^cards/(?P<dummy>[\w\d\-]+)?\-(?P<collection>\d+)$'),
        CollectionCardView.as_view(),
        name='cards-list'),
    url(_(r'^figures/(?P<dummy>[\w\d\-]+)?\-(?P<collection>\d+)$'),
        CollectionFigureView.as_view(),
        name='figures-list'),

    url(_(r'^cards/(?P<collection>[\w\d\-]+)?/(?P<dummy>[\w\d\-]+)?-(?P<amiibo>[\w\d\-]+)$'),
        AmiiboCardView.as_view(),
        name='card-detail'),
    url(_(r'^figures/(?P<collection>[\w\d\-]+)?/(?P<dummy>[\w\d\-]+)?-(?P<amiibo>[\w\d\-]+)$'),
        AmiiboFigureView.as_view(),
        name='figure-detail'),

    url(_(r'^amiibo/(?P<amiibo>\d+)/(?P<action>[\w\+\-\=]+)$'),
        UserAmiiboView.as_view(),
        name='user-action'),
)

amiibofindr/apps/home/urls.py
# coding: utf-8

# django
from django.conf.urls import url, patterns

# home
from .views import HomeView


urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home'),
)

amiibofindr/apps/profile/urls.py
# coding: utf-8

# django
from django.conf.urls import url, patterns
from django.utils.translation import ugettext_lazy as _

# home
from .views import ProfileView


urlpatterns = patterns(
    '',
    url(_(r'^profile/(?P<username>[\w\d\-]+)/$'),
          ProfileView.as_view(),
          name='main'),
    url(_(r'^profile/(?P<username>[\w\d\-]+)/(?P<type>\w+)/(?P<relation>\w+)/$'),
          ProfileView.as_view(),
          name='main-filter'),

)

amiibofindr/urls.py
# django
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _


handler404 = 'amiibofindr.apps.core.views.error404'
handler500 = 'amiibofindr.apps.core.views.error500'


urlpatterns = patterns(
    '',
    url(r'^amiibofindr-admin/', include(admin.site.urls)),
)

urlpatterns += i18n_patterns(
    url(_(r'^account/'), include('allauth.urls')),
    url(r'', include('amiibofindr.apps.amiibo.urls', namespace='amiibo')),
    url(r'', include('amiibofindr.apps.home.urls', namespace='home')),
    url(r'', include('amiibofindr.apps.profile.urls', namespace='profile')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amiibofindr/apps/home/models.py
from django.db import models

# Create your models here.

amiibofindr/apps/notifications/models.py
# coding: utf-8

# py3
from __future__ import unicode_literals

# django
from django.db import models


class AmiiboNotification(models.Model):
    amiibo = models.ForeignKey('amiibo.Amiibo', related_name='notifications')
    max_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    interval = models.PositiveIntegerField(default=60*60)
    shops = models.ManyToManyField('amiibo.AmiiboShop', blank=True)

    notify_twitter = models.BooleanField(default=True)

    last_notification = models.DateTimeField(blank=True, null=True)

amiibofindr/apps/shop/models.py
# coding: utf-8

# py3
from __future__ import unicode_literals

# django
from django.db import models


class Shop(models.Model):
    name = models.CharField(max_length=64)
    slug = models.CharField(max_length=64)
    url = models.CharField(max_length=64)
    flag_code = models.CharField(max_length=2, blank=True, null=True)
    referer_id = models.CharField(max_length=64, blank=True, null=True)
    visible = models.BooleanField(default=True)

    class Meta:
        ordering = ('name', )

    def __unicode__(self):
        return self.name

amiibofindr/apps/amiibo/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View

from .models import (
    Collection, Amiibo,
    AmiiboFigure, AmiiboCard,
    UserAmiibo
)
from . import services


class CollectionView(View):
    template = 'amiibo/collection.html'
    type = Amiibo.FIGURE
    model = AmiiboFigure
    section = 'collection'

    def get(self, request, collection=None, dummy=None):
        if collection:
            collection = get_object_or_404(Collection, pk=collection)
            if self.type == self.model.FIGURE:
                amiibo_list = collection.figures.filter(visible=True)
            elif self.type == self.model.CARD:
                amiibo_list = collection.cards.filter(visible=True)
            else:
                amiibo_list = collection.amiibo.filter(visible=True)
        else:
            collection = None
            amiibo_list = self.model.objects.filter(visible=True)

        return render(request, self.template, {
            'selected_collection': collection,
            'amiibo_list': amiibo_list,
            'item': collection,
            'section': self.section,
        })


class CollectionFigureView(CollectionView):
    type = Amiibo.FIGURE
    model = AmiiboFigure


class CollectionCardView(CollectionView):
    template = 'amiibo/collection-cards.html'
    type = Amiibo.CARD
    model = AmiiboCard


class AmiiboView(View):
    section = 'amiibo'
    def get(self, request, collection=None, amiibo=None, dummy=None):
        amiibo_obj = get_object_or_404(self.model,
                                       pk=amiibo,
                                       # collection__slug=collection,
                                       type=self.type)

        return render(request, self.template, {
            'selected_collection': amiibo_obj.collection,
            'amiibo': amiibo_obj,
            'item': amiibo_obj,
            'section': self.section,
            'users_trading': UserAmiibo.objects.filter(
                trade=True, _amiibo_id=amiibo_obj.pk
            ).order_by('user__username'),
        })

class AmiiboFigureView(AmiiboView):
    template = 'amiibo/amiibo-figure.html'
    type = Amiibo.FIGURE
    model = AmiiboFigure


class AmiiboCardView(AmiiboView):
    template = 'amiibo/amiibo-card.html'
    type = Amiibo.CARD
    model = AmiiboCard


class UserAmiiboView(View):
    actions = {
        '+owned': 'add_owned',
        '-owned': 'remove_owned',
        '+wishlist': 'add_wishlist',
        '-wishlist': 'remove_wishlist',
        '+trade': 'add_trade',
        '-trade': 'remove_trade',
        '+-trade': 'toggle_trade',
    }

    ajax = {
        'detail': 'amiibo/widgets/relation_header_buttons.html',
        'list': 'amiibo/widgets/amiibo-card.html',
    }

    def get(self, request, amiibo, action):
        obj = get_object_or_404(Amiibo, pk=amiibo)
        amiibo = obj.as_type()
        if action in self.actions:
            method = getattr(self, self.actions[action], None)
            if method:
                result = method(request, amiibo)
                if result:
                    return result

        # Handle templating
        request_from = request.GET.get('from', None)
        if request_from in self.ajax:
            return render(request, self.ajax[request_from],
                          { 'amiibo': amiibo, 'request': request })

        return HttpResponseRedirect(amiibo.as_type().get_absolute_url())

    def add_wishlist(self, request, amiibo):
        services.user_add_wishlist(request.user, amiibo)
        # TODO: Add message

    def remove_wishlist(self, request, amiibo):
        services.user_remove_wishlist(request.user, amiibo)
        # TODO: Add message

    def add_trade(self, request, amiibo):
        if services.is_owned_by(amiibo, request.user):
            services.user_add_trade(request.user, amiibo)
            # TODO: Add message

    def remove_trade(self, request, amiibo):
        if services.is_owned_by(amiibo, request.user):
            services.user_remove_trade(request.user, amiibo)
            # TODO: Add message

    def toggle_trade(self, request, amiibo):
        if services.is_owned_by(amiibo, request.user):
            services.user_toggle_trade(request.user, amiibo)
            # TODO: Add message

    def add_owned(self, request, amiibo):
        services.user_add_owned(request.user, amiibo)
        # TODO: Add message

    def remove_owned(self, request, amiibo):
        services.user_remove_owned(request.user, amiibo)
        # TODO: Add message

amiibofindr/apps/core/views.py
# coding: utf-8

# py3
from __future__ import unicode_literals

# django
from django.shortcuts import render_to_response
from django.template import RequestContext


def error404(request):
    template = '404.html'
    response = render_to_response(
        template,
        context_instance=RequestContext(request)
    )
    response.status_code = 404
    return response


def error500(request):
    template = '500.html'
    response = render_to_response(
        template,
        context_instance=RequestContext(request)
    )
    response.status_code = 500
    return response

amiibofindr/apps/home/views.py
# -*- coding: utf-8 -*-

from django.views.generic.base import View
from django.shortcuts import render


class HomeView(View):
    template = 'home/home.html'

    def get(self, request):
        return render(request, self.template, {})

amiibofindr/apps/notifications/views.py
# coding: utf-8

# py3
from __future__ import unicode_literals

amiibofindr/apps/profile/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth import get_user_model
from django.views.generic.base import View
from django.shortcuts import render, get_object_or_404

from amiibofindr.apps.amiibo.models import UserAmiibo, AmiiboFigure, AmiiboCard


class ProfileView(View):
    template = 'profile/main.html'

    types = {
        'figures': ('figure', AmiiboFigure),
        'cards': ('card', AmiiboCard),
    }

    relations = ('own', 'want', 'trade', )

    def get(self, request, username, type='figures', relation='own'):
        user = get_object_or_404(get_user_model(), username=username)
        relation_filter = {relation: True}
        amiibo_pks = UserAmiibo.objects.filter(
            user=user,
            _amiibo__type=self.types[type][0],
            **relation_filter
        ).values_list('_amiibo__id', flat=True)

        amiibo_list = self.types[type][1].objects.filter(pk__in=amiibo_pks)

        return render(request, self.template, {
            'this_user': user,
            'amiibo_list': amiibo_list,
            'type': type,
            'relation': relation,
            'stats': {
                'figures_count': UserAmiibo.objects.filter(
                    user=user, _amiibo__type='figure', own=True).count(),
                'cards_count': UserAmiibo.objects.filter(
                    user=user, _amiibo__type='card', own=True).count(),
            }
        })

amiibofindr/apps/shop/views.py
from django.shortcuts import render

# Create your views here.

amiibofindr/templates/amiibo/widgets/amiibo-card.html
{% load staticfiles thumbnail i18n %}

<div class="ui link card
            {% if amiibo.pk in USER_AMIIBO_WISHLIST %}yellow{% endif %}
            {% if amiibo.pk in USER_AMIIBO_OWNED %}green{% endif %}
            {% if amiibo.pk in USER_AMIIBO_TRADE %}teal{% endif %}"
     data-amiibo-names="{{ amiibo.get_all_names|lower }}"
     data-loader="{{ amiibo.pk }}">
  <a href="{{ amiibo.get_absolute_url }}">
    <div class="image">
      <div class="ui fluid image">
        {% if amiibo.is_card %}
          <img src="{% thumbnail amiibo.image "240x340" crop %}" alt="{{ amiibo.name }}">
        {% else %}
          <img src="{% thumbnail amiibo.image "340x340" crop %}" alt="{{ amiibo.name }}">
        {% endif %}
      </div>
      {% if request.user.is_authenticated %}
        <div class="relation-buttons"
             id="amiibo-buttons-{{ amiibo.pk }}"
             data-handle="relation"
             data-from="list"
             data-amiibo="{{ amiibo.pk }}">
          {% include 'amiibo/widgets/relation_list_buttons.html' %}
        </div>
      {% endif %}
    </div>
    <img src="{% thumbnail amiibo.statue 340x340 crop %}">
  </div>
  <div class="content text-center">
    <a href="{{ amiibo.get_absolute_url }}" class="header">{{ amiibo.name }}</a>
  </div>
</div>

amiibofindr/templates/amiibo/widgets/relation_header_buttons.html
{% load i18n %}

<div {% if user.is_authenticated %}data-handle="relation" data-from="detail"
     data-amiibo="{{ amiibo.pk }}"{% endif %}>
  {% if user.is_authenticated %}
    {% if amiibo.pk in USER_AMIIBO_OWNED %}
      <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='+-trade' %}"
         class="ui button {% if amiibo.pk in USER_AMIIBO_TRADE %}teal{% endif %}">
        <i class="{% if amiibo.pk in USER_AMIIBO_TRADE %}check{% else %}cancel{% endif %} icon"></i> {% trans 'Available for trade' %}
      </a>
      <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='-owned' %}"
         class="ui button red">{% trans 'I do not have it' %}</a>
    {% else %}
      <div class="ui buttons">
        {% if amiibo.pk in USER_AMIIBO_WISHLIST %}
          <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='-wishlist' %}"
             class="ui button yellow">{% trans 'I do not want this' %}</a>
        {% else %}
          <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='+wishlist' %}"
             class="ui button">{% trans 'I want this' %}</a>
        {% endif %}
        <div class="or" data-text="{% trans 'or' %}"></div>
        <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='+owned' %}"
           class="ui positive button">{% trans 'I have this' %}</a>
    {% endif %}
      </div>
  {% else %}
      <form action="{% url 'account_signup' %}" method="get">
        <input type="hidden" name="next" value="{{ amiibo.get_absolute_url }}">
        <button type="submit" class="ui animated fade button standard">
          <div class="visible content ui buttons">
            <a href="#" class="ui button">{% trans 'I want this' %}</a>
            <div class="or" data-text="{% trans 'or' %}"></div>
            <a href="#" class="ui positive button">{% trans 'I have this' %}</a>
          </div>
          <div class="hidden content">
            {% trans 'Register and star collecting amiibo!' %}
          </div>
        </button>
      </form>
  {% endif %}
</div>

amiibofindr/templates/amiibo/widgets/relation_list_buttons.html
{% load i18n %}

{% if amiibo.pk in USER_AMIIBO_OWNED %}
  <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='+-trade' %}"
     class="ui icon button tiny {% if amiibo.pk in USER_AMIIBO_TRADE %}teal{% endif %}">
    <i class="{% if amiibo.pk in USER_AMIIBO_TRADE %}check{% else %}cancel{% endif %} icon"></i>
    <i class="ui icon retweet"></i>
  </a>
  <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='-owned' %}"
     class="ui button icon red tiny"><i class="ui icon cancel"></i></a>
{% else %}
  <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='+owned' %}"
     class="ui button icon  tiny"><i class="ui icon check"></i></a>
  {% if amiibo.pk in USER_AMIIBO_WISHLIST %}
    <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='-wishlist' %}"
       class="ui button icon yellow tiny"><i class="ui icon star"></i></a>
  {% else %}
    <a href="{% url 'amiibo:user-action' amiibo=amiibo.pk action='+wishlist' %}"
       class="ui icon button tiny"><i class="ui icon star"></i></a>
  {% endif %}
{% endif %}