amiibofindr/apps/amiibo/urls.py
# coding: utf-8

# django
from django.conf.urls import url, patterns
from django.utils.translation import ugettext_lazy as _

# home
from .views import (
    AmiiboView, AmiiboCardView, AmiiboFigureView,
    CollectionView, CollectionCardView, CollectionFigureView,
    UserAmiiboView
)

urlpatterns = patterns(
    '',
    url(_('^cards$'),
        CollectionCardView.as_view(),
        name='cards-all'),
    url(_(r'^figures$'),
        CollectionFigureView.as_view(),
        name='figures-all'),

    url(_(r'^cards/(?P<dummy>[\w\d\-]+)?\-(?P<collection>\d+)$'),
        CollectionCardView.as_view(),
        name='cards-list'),
    url(_(r'^figures/(?P<dummy>[\w\d\-]+)?\-(?P<collection>\d+)$'),
        CollectionFigureView.as_view(),
        name='figures-list'),

    url(_(r'^cards/(?P<collection>[\w\d\-]+)?/(?P<dummy>[\w\d\-]+)?-(?P<amiibo>[\w\d\-]+)$'),
        AmiiboCardView.as_view(),
        name='card-detail'),
    url(_(r'^figures/(?P<collection>[\w\d\-]+)?/(?P<dummy>[\w\d\-]+)?-(?P<amiibo>[\w\d\-]+)$'),
        AmiiboFigureView.as_view(),
        name='figure-detail'),

    url(_(r'^amiibo/(?P<amiibo>\d+)/(?P<action>[\w\+\-\=]+)$'),
        UserAmiiboView.as_view(),
        name='user-action'),
)

amiibofindr/apps/home/urls.py
# coding: utf-8

# django
from django.conf.urls import url, patterns

# home
from .views import HomeView


urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home'),
)

amiibofindr/apps/profile/urls.py
# coding: utf-8

# django
from django.conf.urls import url, patterns
from django.utils.translation import ugettext_lazy as _

# home
from .views import ProfileView


urlpatterns = patterns(
    '',
    url(_(r'^profile/(?P<username>[\w\d\-]+)/$'),
          ProfileView.as_view(),
          name='main'),
    url(_(r'^profile/(?P<username>[\w\d\-]+)/(?P<type>\w+)/(?P<relation>\w+)/$'),
          ProfileView.as_view(),
          name='main-filter'),

)

amiibofindr/urls.py
# django
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _


handler404 = 'amiibofindr.apps.core.views.error404'
handler500 = 'amiibofindr.apps.core.views.error500'


urlpatterns = patterns(
    '',
    url(r'^amiibofindr-admin/', include(admin.site.urls)),
)

urlpatterns += i18n_patterns(
    url(_(r'^account/'), include('allauth.urls')),
    url(r'', include('amiibofindr.apps.amiibo.urls', namespace='amiibo')),
    url(r'', include('amiibofindr.apps.home.urls', namespace='home')),
    url(r'', include('amiibofindr.apps.profile.urls', namespace='profile')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amiibofindr/apps/home/models.py
from django.db import models

# Create your models here.

amiibofindr/apps/notifications/models.py
# coding: utf-8

# py3
from __future__ import unicode_literals

# django
from django.db import models


class AmiiboNotification(models.Model):
    amiibo = models.ForeignKey('amiibo.Amiibo', related_name='notifications')
    max_price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    interval = models.PositiveIntegerField(default=60*60)
    shops = models.ManyToManyField('amiibo.AmiiboShop', blank=True)

    notify_twitter = models.BooleanField(default=True)

    last_notification = models.DateTimeField(blank=True, null=True)

amiibofindr/apps/shop/models.py
# coding: utf-8

# py3
from __future__ import unicode_literals

# django
from django.db import models


class Shop(models.Model):
    name = models.CharField(max_length=64)
    slug = models.CharField(max_length=64)
    url = models.CharField(max_length=64)
    flag_code = models.CharField(max_length=2, blank=True, null=True)
    referer_id = models.CharField(max_length=64, blank=True, null=True)
    visible = models.BooleanField(default=True)

    class Meta:
        ordering = ('name', )

    def __unicode__(self):
        return self.name

amiibofindr/apps/amiibo/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View

from .models import (
    Collection, Amiibo,
    AmiiboFigure, AmiiboCard,
    UserAmiibo
)
from . import services


class CollectionView(View):
    template = 'amiibo/collection.html'
    type = Amiibo.FIGURE
    model = AmiiboFigure
    section = 'collection'

    def get(self, request, collection=None, dummy=None):
        if collection:
            collection = get_object_or_404(Collection, pk=collection)
            if self.type == self.model.FIGURE:
                amiibo_list = collection.figures.filter(visible=True)
            elif self.type == self.model.CARD:
                amiibo_list = collection.cards.filter(visible=True)
            else:
                amiibo_list = collection.amiibo.filter(visible=True)
        else:
            collection = None
            amiibo_list = self.model.objects.filter(visible=True)

        return render(request, self.template, {
            'selected_collection': collection,
            'amiibo_list': amiibo_list,
            'item': collection,
            'section': self.section,
        })


class CollectionFigureView(CollectionView):
    type = Amiibo.FIGURE
    model = AmiiboFigure


class CollectionCardView(CollectionView):
    template = 'amiibo/collection-cards.html'
    type = Amiibo.CARD
    model = AmiiboCard


class AmiiboView(View):
    section = 'amiibo'
    def get(self, request, collection=None, amiibo=None, dummy=None):
        amiibo_obj = get_object_or_404(self.model,
                                       pk=amiibo,
                                       # collection__slug=collection,
                                       type=self.type)

        return render(request, self.template, {
            'selected_collection': amiibo_obj.collection,
            'amiibo': amiibo_obj,
            'item': amiibo_obj,
            'section': self.section,
            'users_trading': UserAmiibo.objects.filter(
                trade=True, _amiibo_id=amiibo_obj.pk
            ).order_by('user__username'),
        })

class AmiiboFigureView(AmiiboView):
    template = 'amiibo/amiibo-figure.html'
    type = Amiibo.FIGURE
    model = AmiiboFigure


class AmiiboCardView(AmiiboView):
    template = 'amiibo/amiibo-card.html'
    type = Amiibo.CARD
    model = AmiiboCard


class UserAmiiboView(View):
    actions = {
        '+owned': 'add_owned',
        '-owned': 'remove_owned',
        '+wishlist': 'add_wishlist',
        '-wishlist': 'remove_wishlist',
        '+trade': 'add_trade',
        '-trade': 'remove_trade',
        '+-trade': 'toggle_trade',
    }

    ajax = {
        'detail': 'amiibo/widgets/relation_header_buttons.html',
        'list': 'amiibo/widgets/amiibo-card.html',
    }

    def get(self, request, amiibo, action):
        obj = get_object_or_404(Amiibo, pk=amiibo)
        amiibo = obj.as_type()
        if action in self.actions:
            method = getattr(self, self.actions[action], None)
            if method:
                result = method(request, amiibo)
                if result:
                    return result

        # Handle templating
        request_from = request.GET.get('from', None)
        if request_from in self.ajax:
            return render(request, self.ajax[request_from],
                          { 'amiibo': amiibo, 'request': request })

        return HttpResponseRedirect(amiibo.as_type().get_absolute_url())

    def add_wishlist(self, request, amiibo):
        services.user_add_wishlist(request.user, amiibo)
        # TODO: Add message

    def remove_wishlist(self, request, amiibo):
        services.user_remove_wishlist(request.user, amiibo)
        # TODO: Add message

    def add_trade(self, request, amiibo):
        if services.is_owned_by(amiibo, request.user):
            services.user_add_trade(request.user, amiibo)
            # TODO: Add message

    def remove_trade(self, request, amiibo):
        if services.is_owned_by(amiibo, request.user):
            services.user_remove_trade(request.user, amiibo)
            # TODO: Add message

    def toggle_trade(self, request, amiibo):
        if services.is_owned_by(amiibo, request.user):
            services.user_toggle_trade(request.user, amiibo)
            # TODO: Add message

    def add_owned(self, request, amiibo):
        services.user_add_owned(request.user, amiibo)
        # TODO: Add message

    def remove_owned(self, request, amiibo):
        services.user_remove_owned(request.user, amiibo)
        # TODO: Add message

amiibofindr/apps/core/views.py
# coding: utf-8

# py3
from __future__ import unicode_literals

# django
from django.shortcuts import render_to_response
from django.template import RequestContext


def error404(request):
    template = '404.html'
    response = render_to_response(
        template,
        context_instance=RequestContext(request)
    )
    response.status_code = 404
    return response


def error500(request):
    template = '500.html'
    response = render_to_response(
        template,
        context_instance=RequestContext(request)
    )
    response.status_code = 500
    return response

amiibofindr/apps/home/views.py
# -*- coding: utf-8 -*-

from django.views.generic.base import View
from django.shortcuts import render


class HomeView(View):
    template = 'home/home.html'

    def get(self, request):
        return render(request, self.template, {})

amiibofindr/apps/notifications/views.py
# coding: utf-8

# py3
from __future__ import unicode_literals

amiibofindr/apps/profile/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth import get_user_model
from django.views.generic.base import View
from django.shortcuts import render, get_object_or_404

from amiibofindr.apps.amiibo.models import UserAmiibo, AmiiboFigure, AmiiboCard


class ProfileView(View):
    template = 'profile/main.html'

    types = {
        'figures': ('figure', AmiiboFigure),
        'cards': ('card', AmiiboCard),
    }

    relations = ('own', 'want', 'trade', )

    def get(self, request, username, type='figures', relation='own'):
        user = get_object_or_404(get_user_model(), username=username)
        relation_filter = {relation: True}
        amiibo_pks = UserAmiibo.objects.filter(
            user=user,
            _amiibo__type=self.types[type][0],
            **relation_filter
        ).values_list('_amiibo__id', flat=True)

        amiibo_list = self.types[type][1].objects.filter(pk__in=amiibo_pks)

        return render(request, self.template, {
            'this_user': user,
            'amiibo_list': amiibo_list,
            'type': type,
            'relation': relation,
            'stats': {
                'figures_count': UserAmiibo.objects.filter(
                    user=user, _amiibo__type='figure', own=True).count(),
                'cards_count': UserAmiibo.objects.filter(
                    user=user, _amiibo__type='card', own=True).count(),
            }
        })

amiibofindr/apps/shop/views.py
from django.shortcuts import render

# Create your views here.

amiibofindr/templates/_layout.html
{% load static i18n account socialaccount %}
{% user_display user as user_display %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as languages %}
{% trans 'all' as all_word %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{% static "css/style.css" %}" charset="utf-8">
    <!-- SEO -->
    <meta name=”description” content=”{% block meta_description %}Amiibofindr{% endblock %}”>
    <!-- Twitter -->
    <meta content="{% block meta_twitter_card %}summary{% endblock %}" name="twitter:card" />
    <meta content="{% block meta_twitter_title %}{% endblock %}" name="twitter:title" />
    <meta content="{% block meta_twitter_description %}{% endblock %}" name="twitter:description" />
    <meta content="{% block meta_twitter_image %}{% endblock %}" name="twitter:image:src" />
    <meta content="{% block meta_twitter_url %}{% endblock %}" property="twitter:url" />
    <!-- Facebook -->
    <meta content="{% block meta_og_title %}{% endblock %}" property="og:title" />
    <meta content="{% block meta_og_type %}object{% endblock %}" property="og:type" />
    <meta content="{% block meta_og_image %}{% endblock %}" property="og:image" />
    <meta content="{% block meta_og_url %}{% endblock %}" property="og:url" />
    <meta content="{% block meta_og_description %}{% endblock %}" property="og:description" />
    <title>{% block page_title %}AmiiboFindr{% endblock %}</title>
  </head>

  <body data-views="{% block js_views %}money{% endblock %}">
    {% providers_media_js %}
    <div class="ui page grid">
      <div class="computer tablet only row">
        <div class="ui large menu fluid navbar">
          <a href="{% url 'home:home' %}" class="brand item">Amiibofindr</a>
          <div class="ui dropdown item">
            {% trans "Figures" %}
            <i class="dropdown icon"></i>
            <div class="menu fixzindex">
              <a class="item" href="{% url 'amiibo:figures-all' %}">{% trans "All" %}</a>
              <div class="ui divider"></div>
              {% for col in COLLECTIONS_FIGURES %}
                <a class="item" href="{{ col.get_absolute_url_figures }}">{{ col.name }}</a>
              {% endfor %}
            </div>
          </div>
          <div class="ui dropdown item">
            {% trans "Cards" %}
            <i class="dropdown icon"></i>
            <div class="menu fixzindex">
              <a class="item" href="{% url 'amiibo:cards-all' %}">{% trans "All" %}</a>
              {% for col in COLLECTIONS_CARDS %}
                <a class="item" href="{{ col.get_absolute_url_cards }}">{{ col.name }}</a>
              {% endfor %}
            </div>
          </div>
          <div class="right menu">
            {% if user.is_authenticated %}
              <div class="ui dropdown item">
                <i class="icon user"></i> {{ user_display }}
                <i class="dropdown icon"></i>
                <div class="menu fixzindex">
                  <a class="item" href="{% url 'profile:main' user.username %}">{% trans "My public profile" %}</a>
                  <a class="item" href="{% url 'account_change_password' %}">{% trans "Change password" %}</a>
                  <a class="item" href="{% url 'socialaccount_connections' %}">{% trans "Social accounts" %}</a>
                  <a class="item" href="{% url 'account_email' %}">{% trans "Emails" %}</a>
                  <div class="ui divider"></div>
                  <a class="item" href="{% url 'account_logout' %}">{% trans "Log out" %}</a>
                </div>
              </div>
            {% else %}
                <a class="item" href="{% url 'account_login' %}">{% trans "Login" %}</a>
                <a class="item" href="{% url 'account_signup' %}">{% trans "Register" %}</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="mobile only narrow row">
        <div class="ui large fluid navbar menu">
          <a href="" class="brand item">Amiibofindr</a>
          <div class="right menu">
            <a href="#" class="item toggle-menu">
              <i class="sidebar icon"></i>
            </a>
          </div>
        </div>
        <div class="ui vertical menu responsive-menu">
          {% if user.is_authenticated %}
            <div class="ui item">
              {{ user_display }}
              <div class="menu">
                <a class="item" href="{% url 'profile:main' user.username %}">{% trans "My public profile" %}</a>
                <a class="item" href="{% url 'account_change_password' %}">{% trans "Change password" %}</a>
                <a class="item" href="{% url 'account_email' %}">{% trans "Emails" %}</a>
                <a class="item" href="{% url 'socialaccount_connections' %}">{% trans "Social accounts" %}</a>
                <a class="item" href="{% url 'account_logout' %}">{% trans "Log out" %}</a>
              </div>
            </div>
          {% else %}
            <div class="ui item">
              <div class="menu">
                <a class="item" href="{% url 'account_login' %}">{% trans "Login" %}</a>
                <a class="item" href="{% url 'account_signup' %}">{% trans "Register" %}</a>
              </div>
            </div>
          {% endif %}
          <div class="ui item">
            <div class="text">{% trans 'Figures' %}</div>
            <div class="menu">
              <a class="item" href="{% url 'amiibo:figures-all' %}">{% trans "All" %}</a>
              {% for col in COLLECTIONS_FIGURES %}
                <a class="item" href="{{ col.get_absolute_url_figures }}">{{ col.name }}</a>
              {% endfor %}
            </div>
          </div>
          <div class="ui item">
            <div class="text">{% trans "Cards" %}</div>
            <div class="menu">
              <a class="item" href="{% url 'amiibo:cards-all' %}">{% trans "All" %}</a>
              {% for col in COLLECTIONS_CARDS %}
                <a class="item" href="{{ col.get_absolute_url_cards }}">{{ col.name }}</a>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      <div class="ui breadcrumb">
        {% block breadcrumb %}{% if section %}<strong>Amiibofindr</strong>{% endif %}{% endblock %}
      </div>
    </div>

    {% if messages %}
      <div class="ui page grid">
        <div class="sixteen wide column">
          {% for message in messages %}
            <div class="ui message {{ message.tags }}">{{ message }}</div>
          {% endfor %}

        </div>
      </div>
    {% endif %}

    {% block main_content %}{% endblock %}
    <hr />
    <div class="ui stackable page grid">
      <div class="four wide column">
        <h4>{% trans "Select desired currency" %}</h4>
        <div class="ui link list">
          {% for currency in CURRENCIES %}
            <a class="item" href="#" data-currency-change="{{ currency }}">{{ currency }}</a>
          {% endfor %}
          <a class="item" href="#" data-currency-change="reset">{% trans 'No convert' %}</a>
        </div>
      </div>
      <div class="four wide column left aligned">
        <h4>{% trans "Language" %}</h4>

        <div class="ui link list">
          {% for language in LANGUAGES %}
            {% language language.code %}
            <a class="item {% if language.code == LANGUAGE_CODE %}active{% endif %}"
               href="{{ language.url }}">{{ language.name }}</a>
            {% endlanguage %}
          {% endfor %}
        </div>
      </div>
      <div class="four wide column left aligned"></div>
      <div class="four wide column left aligned">
        <h4>AmiiboFindr</h4>
        <div class="ui link list">
          <a class="item" href="https://twitter.com/amiibofindr" target="_blank"><i class="ui icon twitter"></i>Twitter</a>
          <a class="item" href="https://www.facebook.com/amiibofindr" target="_blank"><i class="ui icon facebook"></i>Facebook</a>
          <a class="item" href="mailto:amiibofindr@fmartingr.com"><i class="ui icon envelope"></i> Email</a>
        </div>
      </div>
    </div>
    {% if not DEBUG %}
      <script>
       (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
           (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
       })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
       ga('create', 'UA-64407848-1', 'auto');
       ga('send', 'pageview');
      </script>
    {% endif %}
    <script type="text/javascript">
     var DEBUG = {{ DEBUG|yesno:"true,false" }};
     var MEDIA_URL = '{{ MEDIA_URL }}';
     var CURRENCIES = ['{{ CURRENCIES|join:"', '" }}'];
    </script>
    <script type="text/javascript" src="{% static "dist/app.js" %}" async defer></script>
  </body>
</html>

amiibofindr/templates/email_confirm.html
{% extends "account/_layout.html" %}

{% load i18n %}
{% load account %}

{% block page_title %}{% trans "Confirm E-mail Address" %} | {{ block.super }}{% endblock %}


{% block main_content %}
  <div class="ui page stacked grid centered">
    <div class="ten wide column">
      <h1>{% trans "Confirm E-mail Address" %}</h1>

      <div class="ui tall stacked segment">
        {% if confirmation %}

          {% user_display confirmation.email_address.user as user_display %}

          <p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

          <form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
            {% csrf_token %}
            <button type="submit" class="ui button primary">{% trans 'Confirm' %}</button>
          </form>

        {% else %}

          {% url 'account_email' as email_url %}

          <p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}