amiibofindr/apps/amiibo/urls.py
# coding: utf-8

# django
from django.conf.urls import url, patterns
from django.utils.translation import ugettext_lazy as _

# home
from .views import (
    AmiiboView, AmiiboCardView, AmiiboFigureView,
    CollectionView, CollectionCardView, CollectionFigureView,
    UserAmiiboView
)

urlpatterns = patterns(
    '',
    url(_('^cards$'),
        CollectionCardView.as_view(),
        name='cards-all'),
    url(_(r'^figures$'),
        CollectionFigureView.as_view(),
        name='figures-all'),

    url(_(r'^cards/(?P<dummy>[\w\d\-]+)?\-(?P<collection>\d+)$'),
        CollectionCardView.as_view(),
        name='cards-list'),
    url(_(r'^figures/(?P<dummy>[\w\d\-]+)?\-(?P<collection>\d+)$'),
        CollectionFigureView.as_view(),
        name='figures-list'),

    url(_(r'^cards/(?P<collection>[\w\d\-]+)?/(?P<dummy>[\w\d\-]+)?-(?P<amiibo>[\w\d\-]+)$'),
        AmiiboCardView.as_view(),
        name='card-detail'),
    url(_(r'^figures/(?P<collection>[\w\d\-]+)?/(?P<dummy>[\w\d\-]+)?-(?P<amiibo>[\w\d\-]+)$'),
        AmiiboFigureView.as_view(),
        name='figure-detail'),

    url(_(r'^amiibo/(?P<amiibo>\d+)/(?P<action>[\w\+\-\=]+)$'),
        UserAmiiboView.as_view(),
        name='user-action'),
)

amiibofindr/apps/home/urls.py
# coding: utf-8

# django
from django.conf.urls import url, patterns

# home
from .views import HomeView


urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home'),
)

amiibofindr/apps/profile/urls.py
# coding: utf-8

# django
from django.conf.urls import url, patterns
from django.utils.translation import ugettext_lazy as _

# home
from .views import ProfileView


urlpatterns = patterns(
    '',
    url(_(r'^profile/(?P<username>[\w\d\-]+)/$'),
          ProfileView.as_view(),
          name='main'),
    url(_(r'^profile/(?P<username>[\w\d\-]+)/(?P<type>\w+)/(?P<relation>\w+)/$'),
          ProfileView.as_view(),
          name='main-filter'),

)

amiibofindr/urls.py
# django
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _


handler404 = 'amiibofindr.apps.core.views.error404'
handler500 = 'amiibofindr.apps.core.views.error500'


urlpatterns = patterns(
    '',
    url(r'^amiibofindr-admin/', include(admin.site.urls)),
)

urlpatterns += i18n_patterns(
    url(_(r'^account/'), include('allauth.urls')),
    url(r'', include('amiibofindr.apps.amiibo.urls', namespace='amiibo')),
    url(r'', include('amiibofindr.apps.home.urls', namespace='home')),
    url(r'', include('amiibofindr.apps.profile.urls', namespace='profile')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amiibofindr/apps/amiibo/models.py
# coding: utf-8

import os

from django.apps import apps
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _, get_language

from amazonify import amazonify

from amiibofindr.apps.shop.crawlers import Crawler


#
# Upload_to helpers
def image_statue_upload(self, filename):
    name, extension = os.path.splitext(filename)
    return 'amiibos/{}/{}{}'.format(
        self.collection.slug, self.slug, extension)

def image_box_upload(self, filename):
    name, extension = os.path.splitext(filename)
    return 'amiibos/{}/{}-box{}'.format(
        self.collection.slug, self.slug, extension)

def image_card_upload(self, filename):
    name, extension = os.path.splitext(filename)
    return 'amiibos/c/{}/{}_{}{}'.format(
        self.collection.pk, self.collection_number, self.pk, extension)

def shop_item_upload(self, filename):
    name, extension = os.path.splitext(filename)
    return 'amiibos/si/{}_{}{}'.format(
        self.shop.pk, self.pk, extension)



#
# Models
class Collection(models.Model):
    slug = models.SlugField(max_length=128)

    name_en = models.CharField(max_length=64, blank=True, null=True)
    name_es = models.CharField(max_length=64, blank=True, null=True)
    name_fr = models.CharField(max_length=64, blank=True, null=True)
    name_it = models.CharField(max_length=64, blank=True, null=True)
    name_de = models.CharField(max_length=64, blank=True, null=True)

    name_eu = models.CharField(max_length=128)
    name_jp = models.CharField(max_length=128, blank=True, null=True)
    name_us = models.CharField(max_length=128, blank=True, null=True)

    @models.permalink
    def get_absolute_url(self):
        return ('amiibo:figures-list', (slugify(self.name), self.pk))

    def get_absolute_url_figures(self):
        return reverse('amiibo:figures-list', args=(slugify(self.name), self.pk))

    def get_absolute_url_cards(self):
        return reverse('amiibo:cards-list', args=(slugify(self.name), self.pk))

    @property
    def amiibos(self):
        return self.amiibos_qs.all()

    @property
    def figures(self):
        return AmiiboFigure.objects.filter(collection_id=self.pk)

    @property
    def cards(self):
        return AmiiboCard.objects.filter(collection_id=self.pk)

    @property
    def name(self):
        name = getattr(self, 'name_{}'.format(get_language()), None)

        if name:
            return name

        if self.name_en:
            return self.name_en

        return self.name_eu

    def __unicode__(self):
        return unicode(self.name_eu) or u''


class Amiibo(models.Model):
    FIGURE = 'figure'
    CARD = 'card'
    AMIIBO_TYPES = (
        (FIGURE, 'Figure'),
        (CARD, 'Card'),
    )

    collection = models.ForeignKey(Collection, related_name='amiibos_qs')
    collection_number = models.IntegerField(blank=True, null=True)
    type = models.CharField(max_length=9, default=FIGURE, choices=AMIIBO_TYPES)

    model_number = models.CharField(max_length=20, blank=True, null=True)

    slug = models.SlugField(max_length=64)

    name_en = models.CharField(max_length=64, blank=True, null=True)
    name_es = models.CharField(max_length=64, blank=True, null=True)
    name_fr = models.CharField(max_length=64, blank=True, null=True)
    name_it = models.CharField(max_length=64, blank=True, null=True)
    name_de = models.CharField(max_length=64, blank=True, null=True)

    name_eu = models.CharField(max_length=64, blank=True, null=True)
    name_jp = models.CharField(max_length=64, blank=True, null=True)
    name_us = models.CharField(max_length=64, blank=True, null=True)

    # Links
    link_en = models.CharField(max_length=64, blank=True, null=True)
    link_es = models.CharField(max_length=64, blank=True, null=True)
    link_fr = models.CharField(max_length=64, blank=True, null=True)
    link_it = models.CharField(max_length=64, blank=True, null=True)
    link_de = models.CharField(max_length=64, blank=True, null=True)

    link_eu = models.CharField(max_length=255, blank=True, null=True)
    link_jp = models.CharField(max_length=255, blank=True, null=True)
    link_us = models.CharField(max_length=255, blank=True, null=True)

    release_date = models.DateField(null=True, blank=True)

    visible = models.BooleanField(default=True)

    _types = {
        'figure': 'amiibo.AmiiboFigure',
        'card': 'amiibo.AmiiboCard',
    }

    def as_type(self):
        """ Returns the amiibo as the correct type model """
        # TODO: Improve this, because queries. Change to a manager.
        model = apps.get_model(self._types[self.type])
        return model.objects.get(pk=self.pk)

    def get_all_names(self):
        result = u''
        for key, value in self.__dict__.items():
            if u'name_' in key and self.__dict__[key]:
                result += u' {}'.format(self.__dict__[key])

        return result

    @property
    def is_card(self):
        return self.type == self.CARD

    @property
    def is_figure(self):
        return self.type == self.FIGURE

    def __unicode__(self):
        return unicode(self.name_eu) or u''

    @property
    def name(self):
        name = getattr(self, 'name_{}'.format(get_language()), None)

        if name:
            return name

        if self.name_en:
            return self.name_en

        return self.name_eu


class AmiiboFigure(Amiibo):
    statue = models.ImageField(upload_to=image_statue_upload)
    box = models.ImageField(upload_to=image_box_upload, blank=True, null=True)

    @models.permalink
    def get_absolute_url(self):
        return ('amiibo:figure-detail', [self.collection.slug, slugify(self.name), self.pk])

    @property
    def image_box(self):
        return 'images/amiibo/{}/{}-box.jpg'.format(
            self.collection.slug, self.slug
        )

    @property
    def image(self):
        return self.statue

    @property
    def image_statue(self):
        return 'images/amiibo/{}/{}.png'.format(
            self.collection.slug, self.slug
        )


class AmiiboCard(Amiibo):
    ROCK = 'rock'
    PAPER = 'paper'
    SCISSORS = 'scissors'
    RPS_CHOICES = (
        (ROCK, _('Rock')),
        (PAPER, _('Paper')),
        (SCISSORS, _('Scissors')),
    )

    CARD_TYPE_CHOICES = (
        ('alligator', _('Alligator')),
        ('anteater', _('Anteater')),
        ('bear', _('Bear')),
        ('bird', _('Bird')),
        ('bull', _('Bull')),
        ('cat', _('Cat')),
        ('chicken', _('Chicken')),
        ('cow', _('Cow')),
        ('cub', _('Cub')),
        ('deer', _('Deer')),
        ('dog', _('Dog')),
        ('duck', _('Duck')),
        ('eagle', _('Eagle')),
        ('elephant', _('Elephant')),
        ('frog', _('Frog')),
        ('goat', _('Goat')),
        ('gorilla', _('Gorilla')),
        ('hamster', _('Hamster')),
        ('hippo', _('Hippo')),
        ('horse', _('Horse')),
        ('kangaroo', _('Kangaroo')),
        ('koala', _('Koala')),
        ('lion', _('Lion')),
        ('monkey', _('Monkey')),
        ('mouse', _('Mouse')),
        ('octopus', _('Octopus')),
        ('ostrich', _('Ostrich')),
        ('penguin', _('Penguin')),
        ('pig', _('Pig')),
        ('rabbit', _('Rabbit')),
        ('rhino', _('Rhino')),
        ('sheep', _('Sheep')),
        ('special', _('Special')),
        ('squirrel', _('Squirrel')),
        ('tiger', _('Tiger')),
        ('wolf', _('Wolf')),
    )

    image = models.ImageField(upload_to=image_card_upload)
    card_type = models.CharField(max_length=12, default='special')

    dice = models.IntegerField(default=1)
    rps = models.CharField(choices=RPS_CHOICES, default=ROCK, max_length=12)

    class Meta:
        ordering = ('collection', 'collection_number', 'name_eu', )

    def get_card_type_display(self):
        return dict(self.CARD_TYPE_CHOICES)[self.card_type]

    @models.permalink
    def get_absolute_url(self):
        return ('amiibo:card-detail',
                [slugify(self.collection.name), slugify(self.name), self.pk])

    def __unicode__(self):
        return u"{} {}".format(self.collection_number, self.slug)


class AmiiboShop(models.Model):
    FIGURE = '1'
    PACK = '2'

    ITEM_TYPES = (
        (FIGURE, 'Figure'),
        (PACK, 'Pack'),
    )

    amiibo = models.ManyToManyField(Amiibo, related_name='shops_set')
    shop = models.ForeignKey('shop.Shop', related_name='amiibos_set')
    type = models.CharField(choices=ITEM_TYPES, default=FIGURE, max_length=1)
    url = models.TextField()
    item_id = models.CharField(max_length=64)
    check_price = models.BooleanField(default=True)
    shop_name = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField(upload_to=shop_item_upload,
                              null=True, blank=True)

    class Meta:
        ordering = ('shop__name', )

    def get_url(self):
        if self.shop.referer_id:
            return amazonify(self.url, self.shop.referer_id)
        return self.url

    def update_price(self, price, currency):
        price_obj, is_new = AmiiboPrice.objects.get_or_create(
            amiibo_shop_id=self.pk)

        price_obj.price = price
        price_obj.stock = price is not None

        if is_new and currency:
            price_obj.currency = currency

        price_obj.save()

    @property
    def last_price(self):
        return self.price_set.first()

    @property
    def is_pack(self):
        return self.type == self.PACK

    def __unicode__(self):
        return u'{} in {}'.format(self.shop_name, self.shop.name)


class AmiiboPrice(models.Model):
    amiibo_shop = models.ForeignKey(AmiiboShop, related_name='price_set')
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    stock = models.BooleanField(default=False)
    currency = models.CharField(default='EUR', max_length=3)
    date = models.DateTimeField(auto_now=True)

amiibofindr/apps/amiibo/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View

from .models import (
    Collection, Amiibo,
    AmiiboFigure, AmiiboCard,
    UserAmiibo
)
from . import services


class CollectionView(View):
    template = 'amiibo/collection.html'
    type = Amiibo.FIGURE
    model = AmiiboFigure
    section = 'collection'

    def get(self, request, collection=None, dummy=None):
        if collection:
            collection = get_object_or_404(Collection, pk=collection)
            if self.type == self.model.FIGURE:
                amiibo_list = collection.figures.filter(visible=True)
            elif self.type == self.model.CARD:
                amiibo_list = collection.cards.filter(visible=True)
            else:
                amiibo_list = collection.amiibo.filter(visible=True)
        else:
            collection = None
            amiibo_list = self.model.objects.filter(visible=True)

        return render(request, self.template, {
            'selected_collection': collection,
            'amiibo_list': amiibo_list,
            'item': collection,
            'section': self.section,
        })


class CollectionFigureView(CollectionView):
    type = Amiibo.FIGURE
    model = AmiiboFigure


class CollectionCardView(CollectionView):
    template = 'amiibo/collection-cards.html'
    type = Amiibo.CARD
    model = AmiiboCard


class AmiiboView(View):
    section = 'amiibo'
    def get(self, request, collection=None, amiibo=None, dummy=None):
        amiibo_obj = get_object_or_404(self.model,
                                       pk=amiibo,
                                       # collection__slug=collection,
                                       type=self.type)

        return render(request, self.template, {
            'selected_collection': amiibo_obj.collection,
            'amiibo': amiibo_obj,
            'item': amiibo_obj,
            'section': self.section,
            'users_trading': UserAmiibo.objects.filter(
                trade=True, _amiibo_id=amiibo_obj.pk
            ).order_by('user__username'),
        })

class AmiiboFigureView(AmiiboView):
    template = 'amiibo/amiibo-figure.html'
    type = Amiibo.FIGURE
    model = AmiiboFigure


class AmiiboCardView(AmiiboView):
    template = 'amiibo/amiibo-card.html'
    type = Amiibo.CARD
    model = AmiiboCard


class UserAmiiboView(View):
    actions = {
        '+owned': 'add_owned',
        '-owned': 'remove_owned',
        '+wishlist': 'add_wishlist',
        '-wishlist': 'remove_wishlist',
        '+trade': 'add_trade',
        '-trade': 'remove_trade',
        '+-trade': 'toggle_trade',
    }

    ajax = {
        'detail': 'amiibo/widgets/relation_header_buttons.html',
        'list': 'amiibo/widgets/amiibo-card.html',
    }

    def get(self, request, amiibo, action):
        obj = get_object_or_404(Amiibo, pk=amiibo)
        amiibo = obj.as_type()
        if action in self.actions:
            method = getattr(self, self.actions[action], None)
            if method:
                result = method(request, amiibo)
                if result:
                    return result

        # Handle templating
        request_from = request.GET.get('from', None)
        if request_from in self.ajax:
            return render(request, self.ajax[request_from],
                          { 'amiibo': amiibo, 'request': request })

        return HttpResponseRedirect(amiibo.as_type().get_absolute_url())

    def add_wishlist(self, request, amiibo):
        services.user_add_wishlist(request.user, amiibo)
        # TODO: Add message

    def remove_wishlist(self, request, amiibo):
        services.user_remove_wishlist(request.user, amiibo)
        # TODO: Add message

    def add_trade(self, request, amiibo):
        if services.is_owned_by(amiibo, request.user):
            services.user_add_trade(request.user, amiibo)
            # TODO: Add message

    def remove_trade(self, request, amiibo):
        if services.is_owned_by(amiibo, request.user):
            services.user_remove_trade(request.user, amiibo)
            # TODO: Add message

    def toggle_trade(self, request, amiibo):
        if services.is_owned_by(amiibo, request.user):
            services.user_toggle_trade(request.user, amiibo)
            # TODO: Add message

    def add_owned(self, request, amiibo):
        services.user_add_owned(request.user, amiibo)
        # TODO: Add message

    def remove_owned(self, request, amiibo):
        services.user_remove_owned(request.user, amiibo)
        # TODO: Add message

amiibofindr/apps/home/views.py
# -*- coding: utf-8 -*-

from django.views.generic.base import View
from django.shortcuts import render


class HomeView(View):
    template = 'home/home.html'

    def get(self, request):
        return render(request, self.template, {})

amiibofindr/apps/notifications/views.py
# coding: utf-8

# py3
from __future__ import unicode_literals

amiibofindr/templates/amiibo/amiibo-card.html
{% extends "amiibo/amiibo-figure.html" %}
{% load thumbnail i18n %}

{% block amiibo_image %}
  <img src="{% thumbnail amiibo.image 300x440 crop %}" class="ui image centered" />
{% endblock %}

{% block amiibo_header %}
  {{ block.super }}
  <div class="ui label">
    {% trans "Number" %}
    <div class="detail">{{ amiibo.collection_number }}</div>
  </div>
  <div class="ui label">
    {% trans "Type" %}
    <div class="detail">{{ amiibo.get_card_type_display }}</div>
  </div>
  <div class="ui label">
    {% trans "RPS" %}
    <div class="detail">{{ amiibo.get_rps_display }}</div>
  </div>
  <div class="ui label">
    {% trans "Dice" %}
    <div class="detail">{{ amiibo.dice }}</div>
  </div>
{% endblock %}

amiibofindr/templates/amiibo/amiibo-figure.html
{% extends "_layout.html" %}

{% comment %}
AMIIBO FIGURE
{% endcomment %}

{% load i18n staticfiles thumbnail gravatar %}

{% block page_title %}{% blocktrans with collection=selected_collection.name amiibo=amiibo.name %}{{ amiibo }} amiibo from {{ collection }} in {% endblocktrans %}{{ block.super }}{% endblock %}

{% block meta_twitter_title %}{% blocktrans with collection=selected_collection.name amiibo=amiibo.name %}{{ amiibo }} amiibo from {{ collection }} in {% endblocktrans %}{{ block.super }}{% endblock %}
{% block meta_og_title %}{% blocktrans with collection=selected_collection.name amiibo=amiibo.name %}{{ amiibo }} amiibo from {{ collection }} in {% endblocktrans %}{{ block.super }}{% endblock %}

{% block meta_twitter_image %}{% thumbnail amiibo.statue 300x300 %}{% endblock %}
{% block meta_og_image %}{% thumbnail amiibo.statue 300x300 %}{% endblock %}

{% block meta_twitter_url %}{{ amiibo.get_absolute_url }}{% endblock %}
{% block meta_og_url %}{{ amiibo.get_absolute_url }}{% endblock %}

{% block js_views %}money,time,relation{% endblock %}

{% block breadcrumb %}
  {{ block.super }}
  <i class="right chevron icon divider"></i>
  <a class="section" href="{{ selected_collection.get_absolute_url }}">{{ selected_collection.name }}</a>
  <i class="right chevron icon divider"></i>
  <span class="active section">{{ amiibo.name }}</span>
{% endblock %}

{% block main_content %}
  <div class="ui page grid">
    <div class="sixteen wide column">
      <div class="ui segment" data-loader="{{ amiibo.pk }}">
        <div class="ui stackable grid">
          <div class="eight wide column ui middle aligned">
            {% block amiibo_header %}
              <h2 class="ui header">
                {{ amiibo.collection.name }}: {{ amiibo.name }}
              </h2>
            {% endblock %}
          </div>
          <div class="eight wide column right aligned">
            {% include 'amiibo/widgets/relation_header_buttons.html' %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="ui page stackable grid">
    <div class="four wide column">
      <div class="ui segment">
        {% block amiibo_image %}
          <img src="{% thumbnail amiibo.statue 340x340 crop %}" class="ui image centered" />
        {% endblock %}
      </div>
    </div>
    <div class="twelve wide column">
      <div class="ui top attached tabular menu">
        <div class="active item" data-tab="shops">{% trans "Shops" %}</div>
        <div class="item" data-tab="users-trading">{% trans "Users trading" %}</div>
      </div>
      <!-- Shops --!>
      <div class="ui bottom attached active tab segment" data-tab="shops">
        {% if amiibo.shops_set.exists %}
          <div class="ui divided items">
            {% for shop_item in amiibo.shops_set.all %}
              {% with price=shop_item.last_price.price stock=shop_item.last_price.stock currency=shop_item.last_price.currency %}
                <div class="item">
                  <div class="content">
                    {% if stock and price %}
                      <a class="ui right floated label green large" href="{{ shop_item.get_url }}"
                         target="_blank">
                        <i class="shop icon"></i>
                        {% trans 'Buy now for' %}
                        <span data-price="{{ price }}" data-currency="{{ currency }}" data-money>
                          {{ price }} {{ currency }}
                        </span>
                      </a>
                    {% else %}
                      <div class="ui right floated label red">
                        {% trans "No stock" %}
                      </div>
                    {% endif %}
                    <a class="header" href="{{ shop_item.get_url }}" target="_blank">{{ shop_item.shop.name }}</a>
                    <div class="meta">
                      <div class="cinema">
                        {% if shop_item.last_price.date %}
                          <i class="ui icon info circle blue"></i>
                          {% trans "Updated" %} <span data-relative="{{ shop_item.last_price.date.isoformat }}"></span><br>
                        {% else %}
                          <i class="ui icon warning circle red"></i>
                          {% trans "This item had never been in stock" %}
                        {% endif %}
                      </div>
                      <div class="cinema">
                        {% if shop_item.is_pack %}
                          <i class="icon cube"></i>
                          {% trans "This is a pack of various items" %}
                        {% endif %}
                      </div>
                    </div>
                  </div>
              {% endwith %}
                </div>
            {% endfor %}
          </div>
        {% else %}
          {% trans "No shops :(" %}
        {% endif %}
      </div>
      <!-- Shops --!>
      <div class="ui bottom attached tab segment" data-tab="users-trading">
        <div class="ui five doubling cards">
          {% for relation in users_trading %}
            <div class="ui link card">
              <a href="{{ amiibo.get_absolute_url }}">
                <div class="image">
                  <div class="ui fluid image">
                    <img src="{% gravatar relation.user %}">
                  </div>
                </div>
              </a>
              <div class="content text-center">
                <a class="bold" href="{% url 'profile:main' relation.user.username %}">{{ relation.user.username }}</a>
              </div>
            </div>
          {% empty %}
            <p>{% trans "No user have this amiibo available for trade :(" %}</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

amiibofindr/templates/amiibo/collection-cards.html
{% extends "amiibo/collection.html" %}
{% load i18n staticfiles %}

{% block main_content %}
  <div class="ui page grid">
    <div class="sixteen wide column">
      {% if selected_collection.name %}<h1>{{ selected_collection.name }}</h1>{% endif %}
      <div class="ui icon big fluid input">
        <input type="text" placeholder="{% trans 'Search...' %}" data-component="collectionSearchInput">
        <i class="inverted circular cancel link icon" data-component="collectionSearchReset"></i>
      </div>
    </div>
    <div class="sixteen wide column">
      <div class="ui six doubling cards" data-component="collectionList">
        {% for amiibo in amiibo_list %}
          {% include "amiibo/widgets/amiibo-card.html" with amiibo=amiibo %}
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

amiibofindr/templates/amiibo/collection.html
{% extends "_layout.html" %}
{% load i18n staticfiles %}

{% block page_title %}{% blocktrans with collection=selected_collection.name %}{{ collection }} amiibos in {% endblocktrans %}{{ block.super }}{% endblock %}

{% block meta_twitter_title %}{% blocktrans with collection=selected_collection.name %}{{ collection }} amiibos in {% endblocktrans %}{{ block.super }}{% endblock %}
{% block meta_og_title %}{% blocktrans with collection=selected_collection.name %}{{ collection }} amiibos in {% endblocktrans %}{{ block.super }}{% endblock %}

{% block meta_twitter_url %}{{ amiibo.get_absolute_url }}{% endblock %}
{% block meta_og_url %}{{ amiibo.get_absolute_url }}{% endblock %}

{% block breadcrumb %}
  {{ block.super }}
  <i class="right chevron icon divider"></i>
  {% if selected_collection %}
    <span class="active section">{{ selected_collection.name }}</span>
  {% else %}
    <span class="active section">{% trans "All amiibo" %}</span>
  {% endif %}
{% endblock %}

{% block js_views %}{{ block.super }},collection-search,relation{% endblock %}

{% block main_content %}
  <div class="ui page grid">
    <div class="sixteen wide column">
      {% if selected_collection.name %}<h1>{{ selected_collection.name }}</h1>{% endif %}
      <div class="ui icon big fluid input">
        <input type="text" placeholder="{% trans 'Search...' %}" data-component="collectionSearchInput">
        <i class="inverted circular cancel link icon" data-component="collectionSearchReset"></i>
      </div>
    </div>
    <div class="sixteen wide column">
      <div class="ui five doubling cards" data-component="collectionList">
        {% for amiibo in amiibo_list %}
          {% include "amiibo/widgets/amiibo-card.html" with amiibo=amiibo %}
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}